# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0003_group_match_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='group',
        ),
        migrations.RemoveField(
            model_name='result',
            name='team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='championship',
        ),
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='championship.Group', verbose_name='group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='championship',
            name='participates',
            field=models.ManyToManyField(related_name='championship', to='championship.Participation', verbose_name='participates'),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
