# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('championship', '0005_auto_20161010_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='player'),
        ),
        migrations.AddField(
            model_name='championship',
            name='teams',
            field=models.ManyToManyField(to='championship.Team', verbose_name='team'),
        ),
    ]
