# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0007_remove_championship_players_per_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='second_team',
            new_name='guest_team',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='first_team',
            new_name='host_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='first_team_goals',
        ),
        migrations.RemoveField(
            model_name='match',
            name='first_team_home',
        ),
        migrations.RemoveField(
            model_name='match',
            name='second_team_goals',
        ),
        migrations.RemoveField(
            model_name='match',
            name='second_team_home',
        ),
        migrations.AddField(
            model_name='match',
            name='guest_team_goals',
            field=models.IntegerField(blank=True, null=True, verbose_name='guest_team_goals'),
        ),
        migrations.AddField(
            model_name='match',
            name='host_team_goals',
            field=models.IntegerField(blank=True, null=True, verbose_name='host_team_goals'),
        ),
    ]
