# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('groups', models.IntegerField(default=1, verbose_name='groups')),
                ('players_per_group', models.IntegerField(default=1, verbose_name='players_per_group')),
                ('home_and_away', models.BooleanField(default=True, verbose_name='home_and_away')),
            ],
            options={
                'verbose_name_plural': 'Championships',
                'verbose_name': 'Championship',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='player')),
            ],
            options={
                'verbose_name_plural': 'Participation',
                'verbose_name': 'Participation',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'verbose_name': 'Team',
            },
        ),
        migrations.AddField(
            model_name='participation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.Team', verbose_name='team'),
        ),
        migrations.AddField(
            model_name='championship',
            name='participation',
            field=models.ManyToManyField(to='championship.Participation', verbose_name='participation'),
        ),
    ]
