# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championship',
            name='participation',
        ),
        migrations.AddField(
            model_name='championship',
            name='participates',
            field=models.ManyToManyField(to='championship.Participation', verbose_name='participates'),
        ),
    ]
