# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0004_auto_20161010_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championship',
            name='participates',
        ),
        migrations.AddField(
            model_name='participation',
            name='championship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='championship.Championship', verbose_name='championship'),
            preserve_default=False,
        ),
    ]
